#############################################################################
# Makefile for building: dbApplication
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  dbApplication.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile dbApplication.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -IdatabaseManager -Iproducts -Icustomers -Ilogin -Iorders -Iaddress -Ishared/delegates -Ishared/models -Iadministrators -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtSql -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = dbApplication1.0.0
DISTDIR = /home/gustavo/QT-PROJECTS/backup/dbApplication/.tmp/dbApplication1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Sql.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = address/addressdto.cpp \
		address/addressview.cpp \
		databaseManager/qsqlconnectiondialog.cpp \
		orders/loadDetailsDialog.cpp \
		orders/orderdetailview.cpp \
		orderviewer.cpp \
		shared/delegates/quantitytotaldelegate.cpp \
		shared/delegates/comboBoxDelegate.cpp \
		databaseManager/dbmanager.cpp \
		shared/delegates/lineeditordelegate.cpp \
		login/login.cpp \
		main.cpp \
		mainwindow.cpp \
		orders/orderform.cpp \
		orders/ordersview.cpp \
		customers/usersview.cpp \
		customers/userDTO.cpp \
		products/productsdto.cpp \
		products/productsview.cpp \
		shared/delegates/spinboxDelegate.cpp \
		shared/models/queryModel.cpp \
		shared/models/readWriteModel.cpp moc_addressdto.cpp \
		moc_addressview.cpp \
		moc_qsqlconnectiondialog.cpp \
		moc_loadDetailsDialog.cpp \
		moc_orderdetailview.cpp \
		moc_orderviewer.cpp \
		moc_quantitytotaldelegate.cpp \
		moc_comboBoxDelegate.cpp \
		moc_lineeditordelegate.cpp \
		moc_login.cpp \
		moc_mainwindow.cpp \
		moc_orderform.cpp \
		moc_ordersview.cpp \
		moc_usersview.cpp \
		moc_userDTO.cpp \
		moc_productsdto.cpp \
		moc_productsview.cpp \
		moc_spinboxDelegate.cpp \
		moc_queryModel.cpp \
		moc_readWriteModel.cpp
OBJECTS       = addressdto.o \
		addressview.o \
		qsqlconnectiondialog.o \
		loadDetailsDialog.o \
		orderdetailview.o \
		orderviewer.o \
		quantitytotaldelegate.o \
		comboBoxDelegate.o \
		dbmanager.o \
		lineeditordelegate.o \
		login.o \
		main.o \
		mainwindow.o \
		orderform.o \
		ordersview.o \
		usersview.o \
		userDTO.o \
		productsdto.o \
		productsview.o \
		spinboxDelegate.o \
		queryModel.o \
		readWriteModel.o \
		moc_addressdto.o \
		moc_addressview.o \
		moc_qsqlconnectiondialog.o \
		moc_loadDetailsDialog.o \
		moc_orderdetailview.o \
		moc_orderviewer.o \
		moc_quantitytotaldelegate.o \
		moc_comboBoxDelegate.o \
		moc_lineeditordelegate.o \
		moc_login.o \
		moc_mainwindow.o \
		moc_orderform.o \
		moc_ordersview.o \
		moc_usersview.o \
		moc_userDTO.o \
		moc_productsdto.o \
		moc_productsview.o \
		moc_spinboxDelegate.o \
		moc_queryModel.o \
		moc_readWriteModel.o
DIST          = Combinear.qss \
		Medize.qss \
		initialData.sql \
		tableStructure.sql \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		dbApplication.pro address/addressdto.h \
		address/addressview.h \
		administrators/ui_registeradmindialog \
		administrators/userDTO.h \
		databaseManager/qsqlconnectiondialog.h \
		orders/loadDetailsDialog.h \
		orders/orderdetailview.h \
		orderviewer.h \
		shared/delegates/quantitytotaldelegate.h \
		shared/delegates/comboBoxDelegate.h \
		databaseManager/db_config.h \
		databaseManager/dbmanager.h \
		shared/delegates/lineeditordelegate.h \
		login/login.h \
		mainwindow.h \
		orders/orderform.h \
		orders/ordersview.h \
		customers/usersview.h \
		customers/userDTO.h \
		products/productsdto.h \
		products/productsview.h \
		shared/delegates/spinboxDelegate.h \
		shared/models/queryModel.h \
		shared/models/readWriteModel.h address/addressdto.cpp \
		address/addressview.cpp \
		databaseManager/qsqlconnectiondialog.cpp \
		orders/loadDetailsDialog.cpp \
		orders/orderdetailview.cpp \
		orderviewer.cpp \
		shared/delegates/quantitytotaldelegate.cpp \
		shared/delegates/comboBoxDelegate.cpp \
		databaseManager/dbmanager.cpp \
		shared/delegates/lineeditordelegate.cpp \
		login/login.cpp \
		main.cpp \
		mainwindow.cpp \
		orders/orderform.cpp \
		orders/ordersview.cpp \
		customers/usersview.cpp \
		customers/userDTO.cpp \
		products/productsdto.cpp \
		products/productsview.cpp \
		shared/delegates/spinboxDelegate.cpp \
		shared/models/queryModel.cpp \
		shared/models/readWriteModel.cpp
QMAKE_TARGET  = dbApplication
DESTDIR       = 
TARGET        = dbApplication


first: all
####### Build rules

dbApplication: ui_addressdto.h ui_addressview.h ui_qsqlconnectiondialog.h ui_login.h ui_mainwindow.h ui_loadDetailsDialog.h ui_orderdetailview.h ui_orderform.h ui_ordersview.h ui_orderviewer.h ui_productsdto.h ui_productsview.h ui_userscontrolform.h ui_usersview.h ui_userDTO.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: dbApplication.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		dbApplication.pro
	$(QMAKE) -o Makefile dbApplication.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
dbApplication.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile dbApplication.pro

qmake_all: FORCE


all: Makefile dbApplication

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents address/addressdto.h address/addressview.h administrators/ui_registeradmindialog administrators/userDTO.h databaseManager/qsqlconnectiondialog.h orders/loadDetailsDialog.h orders/orderdetailview.h orderviewer.h shared/delegates/quantitytotaldelegate.h shared/delegates/comboBoxDelegate.h databaseManager/db_config.h databaseManager/dbmanager.h shared/delegates/lineeditordelegate.h login/login.h mainwindow.h orders/orderform.h orders/ordersview.h customers/usersview.h customers/userDTO.h products/productsdto.h products/productsview.h shared/delegates/spinboxDelegate.h shared/models/queryModel.h shared/models/readWriteModel.h $(DISTDIR)/
	$(COPY_FILE) --parents address/addressdto.cpp address/addressview.cpp databaseManager/qsqlconnectiondialog.cpp orders/loadDetailsDialog.cpp orders/orderdetailview.cpp orderviewer.cpp shared/delegates/quantitytotaldelegate.cpp shared/delegates/comboBoxDelegate.cpp databaseManager/dbmanager.cpp shared/delegates/lineeditordelegate.cpp login/login.cpp main.cpp mainwindow.cpp orders/orderform.cpp orders/ordersview.cpp customers/usersview.cpp customers/userDTO.cpp products/productsdto.cpp products/productsview.cpp shared/delegates/spinboxDelegate.cpp shared/models/queryModel.cpp shared/models/readWriteModel.cpp $(DISTDIR)/
	$(COPY_FILE) --parents address/addressdto.ui address/addressview.ui databaseManager/qsqlconnectiondialog.ui login/login.ui mainwindow.ui orders/loadDetailsDialog.ui orders/orderdetailview.ui orders/orderform.ui orders/ordersview.ui orders/orderviewer.ui orderviewer.ui products/productsdto.ui products/productsview.ui userscontrolform.ui customers/usersview.ui customers/userDTO.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_addressdto.cpp moc_addressview.cpp moc_qsqlconnectiondialog.cpp moc_loadDetailsDialog.cpp moc_orderdetailview.cpp moc_orderviewer.cpp moc_quantitytotaldelegate.cpp moc_comboBoxDelegate.cpp moc_lineeditordelegate.cpp moc_login.cpp moc_mainwindow.cpp moc_orderform.cpp moc_ordersview.cpp moc_usersview.cpp moc_userDTO.cpp moc_productsdto.cpp moc_productsview.cpp moc_spinboxDelegate.cpp moc_queryModel.cpp moc_readWriteModel.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_addressdto.cpp moc_addressview.cpp moc_qsqlconnectiondialog.cpp moc_loadDetailsDialog.cpp moc_orderdetailview.cpp moc_orderviewer.cpp moc_quantitytotaldelegate.cpp moc_comboBoxDelegate.cpp moc_lineeditordelegate.cpp moc_login.cpp moc_mainwindow.cpp moc_orderform.cpp moc_ordersview.cpp moc_usersview.cpp moc_userDTO.cpp moc_productsdto.cpp moc_productsview.cpp moc_spinboxDelegate.cpp moc_queryModel.cpp moc_readWriteModel.cpp
moc_addressdto.cpp: address/addressdto.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/gustavo/QT-PROJECTS/backup/dbApplication/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/gustavo/QT-PROJECTS/backup/dbApplication -I/home/gustavo/QT-PROJECTS/backup/dbApplication/databaseManager -I/home/gustavo/QT-PROJECTS/backup/dbApplication/products -I/home/gustavo/QT-PROJECTS/backup/dbApplication/customers -I/home/gustavo/QT-PROJECTS/backup/dbApplication/login -I/home/gustavo/QT-PROJECTS/backup/dbApplication/orders -I/home/gustavo/QT-PROJECTS/backup/dbApplication/address -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/delegates -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/models -I/home/gustavo/QT-PROJECTS/backup/dbApplication/administrators -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include address/addressdto.h -o moc_addressdto.cpp

moc_addressview.cpp: address/addressview.h \
		address/addressdto.h \
		databaseManager/dbmanager.h \
		databaseManager/db_config.h \
		shared/models/readWriteModel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/gustavo/QT-PROJECTS/backup/dbApplication/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/gustavo/QT-PROJECTS/backup/dbApplication -I/home/gustavo/QT-PROJECTS/backup/dbApplication/databaseManager -I/home/gustavo/QT-PROJECTS/backup/dbApplication/products -I/home/gustavo/QT-PROJECTS/backup/dbApplication/customers -I/home/gustavo/QT-PROJECTS/backup/dbApplication/login -I/home/gustavo/QT-PROJECTS/backup/dbApplication/orders -I/home/gustavo/QT-PROJECTS/backup/dbApplication/address -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/delegates -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/models -I/home/gustavo/QT-PROJECTS/backup/dbApplication/administrators -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include address/addressview.h -o moc_addressview.cpp

moc_qsqlconnectiondialog.cpp: databaseManager/qsqlconnectiondialog.h \
		ui_qsqlconnectiondialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/gustavo/QT-PROJECTS/backup/dbApplication/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/gustavo/QT-PROJECTS/backup/dbApplication -I/home/gustavo/QT-PROJECTS/backup/dbApplication/databaseManager -I/home/gustavo/QT-PROJECTS/backup/dbApplication/products -I/home/gustavo/QT-PROJECTS/backup/dbApplication/customers -I/home/gustavo/QT-PROJECTS/backup/dbApplication/login -I/home/gustavo/QT-PROJECTS/backup/dbApplication/orders -I/home/gustavo/QT-PROJECTS/backup/dbApplication/address -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/delegates -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/models -I/home/gustavo/QT-PROJECTS/backup/dbApplication/administrators -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include databaseManager/qsqlconnectiondialog.h -o moc_qsqlconnectiondialog.cpp

moc_loadDetailsDialog.cpp: orders/loadDetailsDialog.h \
		databaseManager/dbmanager.h \
		databaseManager/db_config.h \
		shared/delegates/quantitytotaldelegate.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/gustavo/QT-PROJECTS/backup/dbApplication/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/gustavo/QT-PROJECTS/backup/dbApplication -I/home/gustavo/QT-PROJECTS/backup/dbApplication/databaseManager -I/home/gustavo/QT-PROJECTS/backup/dbApplication/products -I/home/gustavo/QT-PROJECTS/backup/dbApplication/customers -I/home/gustavo/QT-PROJECTS/backup/dbApplication/login -I/home/gustavo/QT-PROJECTS/backup/dbApplication/orders -I/home/gustavo/QT-PROJECTS/backup/dbApplication/address -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/delegates -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/models -I/home/gustavo/QT-PROJECTS/backup/dbApplication/administrators -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include orders/loadDetailsDialog.h -o moc_loadDetailsDialog.cpp

moc_orderdetailview.cpp: orders/orderdetailview.h \
		databaseManager/dbmanager.h \
		databaseManager/db_config.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/gustavo/QT-PROJECTS/backup/dbApplication/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/gustavo/QT-PROJECTS/backup/dbApplication -I/home/gustavo/QT-PROJECTS/backup/dbApplication/databaseManager -I/home/gustavo/QT-PROJECTS/backup/dbApplication/products -I/home/gustavo/QT-PROJECTS/backup/dbApplication/customers -I/home/gustavo/QT-PROJECTS/backup/dbApplication/login -I/home/gustavo/QT-PROJECTS/backup/dbApplication/orders -I/home/gustavo/QT-PROJECTS/backup/dbApplication/address -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/delegates -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/models -I/home/gustavo/QT-PROJECTS/backup/dbApplication/administrators -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include orders/orderdetailview.h -o moc_orderdetailview.cpp

moc_orderviewer.cpp: orderviewer.h \
		databaseManager/dbmanager.h \
		databaseManager/db_config.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/gustavo/QT-PROJECTS/backup/dbApplication/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/gustavo/QT-PROJECTS/backup/dbApplication -I/home/gustavo/QT-PROJECTS/backup/dbApplication/databaseManager -I/home/gustavo/QT-PROJECTS/backup/dbApplication/products -I/home/gustavo/QT-PROJECTS/backup/dbApplication/customers -I/home/gustavo/QT-PROJECTS/backup/dbApplication/login -I/home/gustavo/QT-PROJECTS/backup/dbApplication/orders -I/home/gustavo/QT-PROJECTS/backup/dbApplication/address -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/delegates -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/models -I/home/gustavo/QT-PROJECTS/backup/dbApplication/administrators -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include orderviewer.h -o moc_orderviewer.cpp

moc_quantitytotaldelegate.cpp: shared/delegates/quantitytotaldelegate.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/gustavo/QT-PROJECTS/backup/dbApplication/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/gustavo/QT-PROJECTS/backup/dbApplication -I/home/gustavo/QT-PROJECTS/backup/dbApplication/databaseManager -I/home/gustavo/QT-PROJECTS/backup/dbApplication/products -I/home/gustavo/QT-PROJECTS/backup/dbApplication/customers -I/home/gustavo/QT-PROJECTS/backup/dbApplication/login -I/home/gustavo/QT-PROJECTS/backup/dbApplication/orders -I/home/gustavo/QT-PROJECTS/backup/dbApplication/address -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/delegates -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/models -I/home/gustavo/QT-PROJECTS/backup/dbApplication/administrators -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include shared/delegates/quantitytotaldelegate.h -o moc_quantitytotaldelegate.cpp

moc_comboBoxDelegate.cpp: shared/delegates/comboBoxDelegate.h \
		databaseManager/dbmanager.h \
		databaseManager/db_config.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/gustavo/QT-PROJECTS/backup/dbApplication/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/gustavo/QT-PROJECTS/backup/dbApplication -I/home/gustavo/QT-PROJECTS/backup/dbApplication/databaseManager -I/home/gustavo/QT-PROJECTS/backup/dbApplication/products -I/home/gustavo/QT-PROJECTS/backup/dbApplication/customers -I/home/gustavo/QT-PROJECTS/backup/dbApplication/login -I/home/gustavo/QT-PROJECTS/backup/dbApplication/orders -I/home/gustavo/QT-PROJECTS/backup/dbApplication/address -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/delegates -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/models -I/home/gustavo/QT-PROJECTS/backup/dbApplication/administrators -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include shared/delegates/comboBoxDelegate.h -o moc_comboBoxDelegate.cpp

moc_lineeditordelegate.cpp: shared/delegates/lineeditordelegate.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/gustavo/QT-PROJECTS/backup/dbApplication/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/gustavo/QT-PROJECTS/backup/dbApplication -I/home/gustavo/QT-PROJECTS/backup/dbApplication/databaseManager -I/home/gustavo/QT-PROJECTS/backup/dbApplication/products -I/home/gustavo/QT-PROJECTS/backup/dbApplication/customers -I/home/gustavo/QT-PROJECTS/backup/dbApplication/login -I/home/gustavo/QT-PROJECTS/backup/dbApplication/orders -I/home/gustavo/QT-PROJECTS/backup/dbApplication/address -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/delegates -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/models -I/home/gustavo/QT-PROJECTS/backup/dbApplication/administrators -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include shared/delegates/lineeditordelegate.h -o moc_lineeditordelegate.cpp

moc_login.cpp: login/login.h \
		customers/userDTO.h \
		databaseManager/dbmanager.h \
		databaseManager/db_config.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/gustavo/QT-PROJECTS/backup/dbApplication/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/gustavo/QT-PROJECTS/backup/dbApplication -I/home/gustavo/QT-PROJECTS/backup/dbApplication/databaseManager -I/home/gustavo/QT-PROJECTS/backup/dbApplication/products -I/home/gustavo/QT-PROJECTS/backup/dbApplication/customers -I/home/gustavo/QT-PROJECTS/backup/dbApplication/login -I/home/gustavo/QT-PROJECTS/backup/dbApplication/orders -I/home/gustavo/QT-PROJECTS/backup/dbApplication/address -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/delegates -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/models -I/home/gustavo/QT-PROJECTS/backup/dbApplication/administrators -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include login/login.h -o moc_login.cpp

moc_mainwindow.cpp: mainwindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/gustavo/QT-PROJECTS/backup/dbApplication/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/gustavo/QT-PROJECTS/backup/dbApplication -I/home/gustavo/QT-PROJECTS/backup/dbApplication/databaseManager -I/home/gustavo/QT-PROJECTS/backup/dbApplication/products -I/home/gustavo/QT-PROJECTS/backup/dbApplication/customers -I/home/gustavo/QT-PROJECTS/backup/dbApplication/login -I/home/gustavo/QT-PROJECTS/backup/dbApplication/orders -I/home/gustavo/QT-PROJECTS/backup/dbApplication/address -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/delegates -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/models -I/home/gustavo/QT-PROJECTS/backup/dbApplication/administrators -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_orderform.cpp: orders/orderform.h \
		orders/loadDetailsDialog.h \
		databaseManager/dbmanager.h \
		databaseManager/db_config.h \
		shared/delegates/quantitytotaldelegate.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/gustavo/QT-PROJECTS/backup/dbApplication/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/gustavo/QT-PROJECTS/backup/dbApplication -I/home/gustavo/QT-PROJECTS/backup/dbApplication/databaseManager -I/home/gustavo/QT-PROJECTS/backup/dbApplication/products -I/home/gustavo/QT-PROJECTS/backup/dbApplication/customers -I/home/gustavo/QT-PROJECTS/backup/dbApplication/login -I/home/gustavo/QT-PROJECTS/backup/dbApplication/orders -I/home/gustavo/QT-PROJECTS/backup/dbApplication/address -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/delegates -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/models -I/home/gustavo/QT-PROJECTS/backup/dbApplication/administrators -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include orders/orderform.h -o moc_orderform.cpp

moc_ordersview.cpp: orders/ordersview.h \
		databaseManager/dbmanager.h \
		databaseManager/db_config.h \
		shared/models/readWriteModel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/gustavo/QT-PROJECTS/backup/dbApplication/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/gustavo/QT-PROJECTS/backup/dbApplication -I/home/gustavo/QT-PROJECTS/backup/dbApplication/databaseManager -I/home/gustavo/QT-PROJECTS/backup/dbApplication/products -I/home/gustavo/QT-PROJECTS/backup/dbApplication/customers -I/home/gustavo/QT-PROJECTS/backup/dbApplication/login -I/home/gustavo/QT-PROJECTS/backup/dbApplication/orders -I/home/gustavo/QT-PROJECTS/backup/dbApplication/address -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/delegates -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/models -I/home/gustavo/QT-PROJECTS/backup/dbApplication/administrators -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include orders/ordersview.h -o moc_ordersview.cpp

moc_usersview.cpp: customers/usersview.h \
		shared/models/readWriteModel.h \
		databaseManager/dbmanager.h \
		databaseManager/db_config.h \
		customers/userDTO.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/gustavo/QT-PROJECTS/backup/dbApplication/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/gustavo/QT-PROJECTS/backup/dbApplication -I/home/gustavo/QT-PROJECTS/backup/dbApplication/databaseManager -I/home/gustavo/QT-PROJECTS/backup/dbApplication/products -I/home/gustavo/QT-PROJECTS/backup/dbApplication/customers -I/home/gustavo/QT-PROJECTS/backup/dbApplication/login -I/home/gustavo/QT-PROJECTS/backup/dbApplication/orders -I/home/gustavo/QT-PROJECTS/backup/dbApplication/address -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/delegates -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/models -I/home/gustavo/QT-PROJECTS/backup/dbApplication/administrators -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include customers/usersview.h -o moc_usersview.cpp

moc_userDTO.cpp: customers/userDTO.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/gustavo/QT-PROJECTS/backup/dbApplication/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/gustavo/QT-PROJECTS/backup/dbApplication -I/home/gustavo/QT-PROJECTS/backup/dbApplication/databaseManager -I/home/gustavo/QT-PROJECTS/backup/dbApplication/products -I/home/gustavo/QT-PROJECTS/backup/dbApplication/customers -I/home/gustavo/QT-PROJECTS/backup/dbApplication/login -I/home/gustavo/QT-PROJECTS/backup/dbApplication/orders -I/home/gustavo/QT-PROJECTS/backup/dbApplication/address -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/delegates -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/models -I/home/gustavo/QT-PROJECTS/backup/dbApplication/administrators -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include customers/userDTO.h -o moc_userDTO.cpp

moc_productsdto.cpp: products/productsdto.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/gustavo/QT-PROJECTS/backup/dbApplication/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/gustavo/QT-PROJECTS/backup/dbApplication -I/home/gustavo/QT-PROJECTS/backup/dbApplication/databaseManager -I/home/gustavo/QT-PROJECTS/backup/dbApplication/products -I/home/gustavo/QT-PROJECTS/backup/dbApplication/customers -I/home/gustavo/QT-PROJECTS/backup/dbApplication/login -I/home/gustavo/QT-PROJECTS/backup/dbApplication/orders -I/home/gustavo/QT-PROJECTS/backup/dbApplication/address -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/delegates -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/models -I/home/gustavo/QT-PROJECTS/backup/dbApplication/administrators -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include products/productsdto.h -o moc_productsdto.cpp

moc_productsview.cpp: products/productsview.h \
		databaseManager/dbmanager.h \
		databaseManager/db_config.h \
		shared/delegates/spinboxDelegate.h \
		shared/delegates/comboBoxDelegate.h \
		products/productsdto.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/gustavo/QT-PROJECTS/backup/dbApplication/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/gustavo/QT-PROJECTS/backup/dbApplication -I/home/gustavo/QT-PROJECTS/backup/dbApplication/databaseManager -I/home/gustavo/QT-PROJECTS/backup/dbApplication/products -I/home/gustavo/QT-PROJECTS/backup/dbApplication/customers -I/home/gustavo/QT-PROJECTS/backup/dbApplication/login -I/home/gustavo/QT-PROJECTS/backup/dbApplication/orders -I/home/gustavo/QT-PROJECTS/backup/dbApplication/address -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/delegates -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/models -I/home/gustavo/QT-PROJECTS/backup/dbApplication/administrators -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include products/productsview.h -o moc_productsview.cpp

moc_spinboxDelegate.cpp: shared/delegates/spinboxDelegate.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/gustavo/QT-PROJECTS/backup/dbApplication/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/gustavo/QT-PROJECTS/backup/dbApplication -I/home/gustavo/QT-PROJECTS/backup/dbApplication/databaseManager -I/home/gustavo/QT-PROJECTS/backup/dbApplication/products -I/home/gustavo/QT-PROJECTS/backup/dbApplication/customers -I/home/gustavo/QT-PROJECTS/backup/dbApplication/login -I/home/gustavo/QT-PROJECTS/backup/dbApplication/orders -I/home/gustavo/QT-PROJECTS/backup/dbApplication/address -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/delegates -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/models -I/home/gustavo/QT-PROJECTS/backup/dbApplication/administrators -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include shared/delegates/spinboxDelegate.h -o moc_spinboxDelegate.cpp

moc_queryModel.cpp: shared/models/queryModel.h \
		databaseManager/dbmanager.h \
		databaseManager/db_config.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/gustavo/QT-PROJECTS/backup/dbApplication/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/gustavo/QT-PROJECTS/backup/dbApplication -I/home/gustavo/QT-PROJECTS/backup/dbApplication/databaseManager -I/home/gustavo/QT-PROJECTS/backup/dbApplication/products -I/home/gustavo/QT-PROJECTS/backup/dbApplication/customers -I/home/gustavo/QT-PROJECTS/backup/dbApplication/login -I/home/gustavo/QT-PROJECTS/backup/dbApplication/orders -I/home/gustavo/QT-PROJECTS/backup/dbApplication/address -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/delegates -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/models -I/home/gustavo/QT-PROJECTS/backup/dbApplication/administrators -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include shared/models/queryModel.h -o moc_queryModel.cpp

moc_readWriteModel.cpp: shared/models/readWriteModel.h \
		databaseManager/dbmanager.h \
		databaseManager/db_config.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/gustavo/QT-PROJECTS/backup/dbApplication/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/gustavo/QT-PROJECTS/backup/dbApplication -I/home/gustavo/QT-PROJECTS/backup/dbApplication/databaseManager -I/home/gustavo/QT-PROJECTS/backup/dbApplication/products -I/home/gustavo/QT-PROJECTS/backup/dbApplication/customers -I/home/gustavo/QT-PROJECTS/backup/dbApplication/login -I/home/gustavo/QT-PROJECTS/backup/dbApplication/orders -I/home/gustavo/QT-PROJECTS/backup/dbApplication/address -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/delegates -I/home/gustavo/QT-PROJECTS/backup/dbApplication/shared/models -I/home/gustavo/QT-PROJECTS/backup/dbApplication/administrators -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include shared/models/readWriteModel.h -o moc_readWriteModel.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_addressdto.h ui_addressview.h ui_qsqlconnectiondialog.h ui_login.h ui_mainwindow.h ui_loadDetailsDialog.h ui_orderdetailview.h ui_orderform.h ui_ordersview.h ui_orderviewer.h ui_orderviewer.h ui_productsdto.h ui_productsview.h ui_userscontrolform.h ui_usersview.h ui_userDTO.h
compiler_uic_clean:
	-$(DEL_FILE) ui_addressdto.h ui_addressview.h ui_qsqlconnectiondialog.h ui_login.h ui_mainwindow.h ui_loadDetailsDialog.h ui_orderdetailview.h ui_orderform.h ui_ordersview.h ui_orderviewer.h ui_orderviewer.h ui_productsdto.h ui_productsview.h ui_userscontrolform.h ui_usersview.h ui_userDTO.h
ui_addressdto.h: address/addressdto.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic address/addressdto.ui -o ui_addressdto.h

ui_addressview.h: address/addressview.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic address/addressview.ui -o ui_addressview.h

ui_qsqlconnectiondialog.h: databaseManager/qsqlconnectiondialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic databaseManager/qsqlconnectiondialog.ui -o ui_qsqlconnectiondialog.h

ui_login.h: login/login.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic login/login.ui -o ui_login.h

ui_mainwindow.h: mainwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_loadDetailsDialog.h: orders/loadDetailsDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic orders/loadDetailsDialog.ui -o ui_loadDetailsDialog.h

ui_orderdetailview.h: orders/orderdetailview.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic orders/orderdetailview.ui -o ui_orderdetailview.h

ui_orderform.h: orders/orderform.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic orders/orderform.ui -o ui_orderform.h

ui_ordersview.h: orders/ordersview.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic orders/ordersview.ui -o ui_ordersview.h

ui_orderviewer.h: orders/orderviewer.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic orders/orderviewer.ui -o ui_orderviewer.h

ui_orderviewer.h: orderviewer.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic orderviewer.ui -o ui_orderviewer.h

ui_productsdto.h: products/productsdto.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic products/productsdto.ui -o ui_productsdto.h

ui_productsview.h: products/productsview.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic products/productsview.ui -o ui_productsview.h

ui_userscontrolform.h: userscontrolform.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic userscontrolform.ui -o ui_userscontrolform.h

ui_usersview.h: customers/usersview.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic customers/usersview.ui -o ui_usersview.h

ui_userDTO.h: customers/userDTO.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic customers/userDTO.ui -o ui_userDTO.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

addressdto.o: address/addressdto.cpp address/addressdto.h \
		login/login.h \
		customers/userDTO.h \
		databaseManager/dbmanager.h \
		databaseManager/db_config.h \
		ui_addressdto.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addressdto.o address/addressdto.cpp

addressview.o: address/addressview.cpp address/addressview.h \
		address/addressdto.h \
		databaseManager/dbmanager.h \
		databaseManager/db_config.h \
		shared/models/readWriteModel.h \
		shared/models/queryModel.h \
		shared/delegates/lineeditordelegate.h \
		login/login.h \
		customers/userDTO.h \
		ui_addressview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addressview.o address/addressview.cpp

qsqlconnectiondialog.o: databaseManager/qsqlconnectiondialog.cpp databaseManager/qsqlconnectiondialog.h \
		ui_qsqlconnectiondialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qsqlconnectiondialog.o databaseManager/qsqlconnectiondialog.cpp

loadDetailsDialog.o: orders/loadDetailsDialog.cpp orders/loadDetailsDialog.h \
		databaseManager/dbmanager.h \
		databaseManager/db_config.h \
		shared/delegates/quantitytotaldelegate.h \
		login/login.h \
		customers/userDTO.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loadDetailsDialog.o orders/loadDetailsDialog.cpp

orderdetailview.o: orders/orderdetailview.cpp orders/orderdetailview.h \
		databaseManager/dbmanager.h \
		databaseManager/db_config.h \
		shared/models/queryModel.h \
		shared/models/readWriteModel.h \
		ui_orderdetailview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o orderdetailview.o orders/orderdetailview.cpp

orderviewer.o: orderviewer.cpp orderviewer.h \
		databaseManager/dbmanager.h \
		databaseManager/db_config.h \
		shared/models/queryModel.h \
		ui_orderviewer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o orderviewer.o orderviewer.cpp

quantitytotaldelegate.o: shared/delegates/quantitytotaldelegate.cpp shared/delegates/quantitytotaldelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quantitytotaldelegate.o shared/delegates/quantitytotaldelegate.cpp

comboBoxDelegate.o: shared/delegates/comboBoxDelegate.cpp shared/delegates/comboBoxDelegate.h \
		databaseManager/dbmanager.h \
		databaseManager/db_config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o comboBoxDelegate.o shared/delegates/comboBoxDelegate.cpp

dbmanager.o: databaseManager/dbmanager.cpp databaseManager/dbmanager.h \
		databaseManager/db_config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dbmanager.o databaseManager/dbmanager.cpp

lineeditordelegate.o: shared/delegates/lineeditordelegate.cpp shared/delegates/lineeditordelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lineeditordelegate.o shared/delegates/lineeditordelegate.cpp

login.o: login/login.cpp login/login.h \
		customers/userDTO.h \
		databaseManager/dbmanager.h \
		databaseManager/db_config.h \
		ui_login.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o login.o login/login.cpp

main.o: main.cpp mainwindow.h \
		databaseManager/dbmanager.h \
		databaseManager/db_config.h \
		login/login.h \
		customers/userDTO.h \
		orders/orderform.h \
		orders/loadDetailsDialog.h \
		shared/delegates/quantitytotaldelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		address/addressdto.h \
		administrators/ui_registeradmindialog.h \
		orders/orderdetailview.h \
		databaseManager/dbmanager.h \
		databaseManager/db_config.h \
		address/addressview.h \
		shared/models/readWriteModel.h \
		login/login.h \
		customers/userDTO.h \
		orders/orderform.h \
		orders/loadDetailsDialog.h \
		shared/delegates/quantitytotaldelegate.h \
		orders/ordersview.h \
		products/productsdto.h \
		products/productsview.h \
		shared/delegates/spinboxDelegate.h \
		shared/delegates/comboBoxDelegate.h \
		ui_mainwindow.h \
		customers/usersview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

orderform.o: orders/orderform.cpp orders/orderform.h \
		orders/loadDetailsDialog.h \
		databaseManager/dbmanager.h \
		databaseManager/db_config.h \
		shared/delegates/quantitytotaldelegate.h \
		login/login.h \
		customers/userDTO.h \
		ui_orderform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o orderform.o orders/orderform.cpp

ordersview.o: orders/ordersview.cpp shared/models/queryModel.h \
		databaseManager/dbmanager.h \
		databaseManager/db_config.h \
		orders/ordersview.h \
		shared/models/readWriteModel.h \
		ui_ordersview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ordersview.o orders/ordersview.cpp

usersview.o: customers/usersview.cpp customers/usersview.h \
		shared/models/readWriteModel.h \
		databaseManager/dbmanager.h \
		databaseManager/db_config.h \
		customers/userDTO.h \
		shared/delegates/lineeditordelegate.h \
		ui_usersview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o usersview.o customers/usersview.cpp

userDTO.o: customers/userDTO.cpp customers/userDTO.h \
		administrators/ui_registeradmindialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o userDTO.o customers/userDTO.cpp

productsdto.o: products/productsdto.cpp products/productsdto.h \
		ui_productsdto.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o productsdto.o products/productsdto.cpp

productsview.o: products/productsview.cpp products/productsview.h \
		databaseManager/dbmanager.h \
		databaseManager/db_config.h \
		shared/delegates/spinboxDelegate.h \
		shared/delegates/comboBoxDelegate.h \
		products/productsdto.h \
		shared/models/readWriteModel.h \
		shared/delegates/lineeditordelegate.h \
		login/login.h \
		customers/userDTO.h \
		ui_productsview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o productsview.o products/productsview.cpp

spinboxDelegate.o: shared/delegates/spinboxDelegate.cpp shared/delegates/spinboxDelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o spinboxDelegate.o shared/delegates/spinboxDelegate.cpp

queryModel.o: shared/models/queryModel.cpp shared/models/queryModel.h \
		databaseManager/dbmanager.h \
		databaseManager/db_config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o queryModel.o shared/models/queryModel.cpp

readWriteModel.o: shared/models/readWriteModel.cpp shared/models/readWriteModel.h \
		databaseManager/dbmanager.h \
		databaseManager/db_config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o readWriteModel.o shared/models/readWriteModel.cpp

moc_addressdto.o: moc_addressdto.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addressdto.o moc_addressdto.cpp

moc_addressview.o: moc_addressview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addressview.o moc_addressview.cpp

moc_qsqlconnectiondialog.o: moc_qsqlconnectiondialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qsqlconnectiondialog.o moc_qsqlconnectiondialog.cpp

moc_loadDetailsDialog.o: moc_loadDetailsDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_loadDetailsDialog.o moc_loadDetailsDialog.cpp

moc_orderdetailview.o: moc_orderdetailview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_orderdetailview.o moc_orderdetailview.cpp

moc_orderviewer.o: moc_orderviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_orderviewer.o moc_orderviewer.cpp

moc_quantitytotaldelegate.o: moc_quantitytotaldelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_quantitytotaldelegate.o moc_quantitytotaldelegate.cpp

moc_comboBoxDelegate.o: moc_comboBoxDelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_comboBoxDelegate.o moc_comboBoxDelegate.cpp

moc_lineeditordelegate.o: moc_lineeditordelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_lineeditordelegate.o moc_lineeditordelegate.cpp

moc_login.o: moc_login.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_login.o moc_login.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_orderform.o: moc_orderform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_orderform.o moc_orderform.cpp

moc_ordersview.o: moc_ordersview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ordersview.o moc_ordersview.cpp

moc_usersview.o: moc_usersview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_usersview.o moc_usersview.cpp

moc_userDTO.o: moc_userDTO.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_userDTO.o moc_userDTO.cpp

moc_productsdto.o: moc_productsdto.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_productsdto.o moc_productsdto.cpp

moc_productsview.o: moc_productsview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_productsview.o moc_productsview.cpp

moc_spinboxDelegate.o: moc_spinboxDelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_spinboxDelegate.o moc_spinboxDelegate.cpp

moc_queryModel.o: moc_queryModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_queryModel.o moc_queryModel.cpp

moc_readWriteModel.o: moc_readWriteModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_readWriteModel.o moc_readWriteModel.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/dbApplication/bin || mkdir -p $(INSTALL_ROOT)/opt/dbApplication/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/dbApplication/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/dbApplication/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/dbApplication/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/dbApplication/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

